### ISSUE TITLE
Player Information Parsing Problems

### ISSUE THREAD

**Issue by grosem** [fnogatz/node-swtparser#2]
I don't know what is unique about this tournament, but parsing [this file](http://www.nsj-online.de/swtparser-master/data/LMM%20U14w.SWT) does not work as expected. Player and club names are cut and there is an issue with the player id.

![image](https://cloud.githubusercontent.com/assets/6620354/26160684/41b57f48-3b22-11e7-93e0-9ae37f4ab5d0.png)

The php parser works well ([see output](http://www.nsj-online.de/swtparser-master/example.php?file=LMM%20U14w.SWT&view=data)). I used the latest structure files in the browser version.

Any ideas?

**Comment by fnogatz** [comment]
This has been fixed in swtparser@1.4.0.
